### ISSUE TITLE
/stuck or similar command

### ISSUE THREAD

**Issue by ZekeSmith** [Patbox/get-off-my-lawn-reserved#10]
It is not uncommon for players to get stuck in bases on multiplayer servers and if an admin is offline it can be nuisance.

I am suggesting a /stuck or similar command maybe even a prompt if they keep trying to interact or mine blocks constantly that are claimed. This would then teleport the user to a random location outside the claim preferably at the highest block location.

**Comment by gadget78** [comment]
i set up a static /spawn command, which players can use to go back to spawn area
(was separate from GOML, i actually used the discord4fabric plugin, and its custom_events)
i believe there are other plugins/mods that could perform this, like essentials plugin maybe ?
