### ISSUE TITLE
[Feature Request] Add claim amount limit

### ISSUE THREAD

**Issue by elhertz** [Patbox/get-off-my-lawn-reserved#11]
I want my players to have only one or two claims available so they don't spam claims everywhere.
This limit could also be world-specific.

Add a permission node to bypass this limit:
- gomlr.claimlimit.bypass (bypasses it completely, perfect for admins or OPs)
- gomlr.claimlimit.bypass.20 (bypasses a specfic amount)
- gomlr.claimlimit.bypass.nether.20 (bypasses a specfic amount only in the nether)

is this possible? thanks

**Comment by Patbox** [comment]
It's already part of the config, through it's not permission specific

**Comment by elhertz** [comment]
> It's already part of the config, through it's not permission specific

Oh I was checking the github for more info about the config (outdated) and I didn't bother to check my own generated config, my mistake, not gonna happen again sorry.
I hope you consider adding permissions. Though it's ok if you don't feel like it's necessary. 
Love your mods patbox, thanks!
