### ISSUE TITLE
Mod decided to not show in rei for some reason

### ISSUE THREAD

**Issue by ilkerbey-01** [Patbox/get-off-my-lawn-reserved#12]
I am sorry to not give any info but stuff doesnt show in rei, which files should I send for helping you solve this?

**Comment by arnokeesman** [comment]
Adding Polymer to the client (assuming you're running GOML-R on a server) should add the items to REI.

**Comment by ilkerbey-01** [comment]
is polymer available on 1.19?

**Comment by arnokeesman** [comment]
Sure is: https://github.com/Patbox/polymer/releases

**Comment by ilkerbey-01** [comment]
oh I was thinking polymorph

**Comment by ilkerbey-01** [comment]
augment craftings and recipes still not showing up tho

**Comment by ilkerbey-01** [comment]
https://i.imgur.com/iYWFhEE.png

**Comment by arnokeesman** [comment]
Then for best support just put GOML-R on client too, recipes should be in vanilla recipe book already. (GOML-R includes Polymer, no need for that anymore)

**Comment by ilkerbey-01** [comment]
its already on client too

**Comment by ilkerbey-01** [comment]
https://i.imgur.com/aNsG0oR.png

**Comment by Patbox** [comment]
It's more of issue with rei/polymer's interaction with it. Closing for now. JEI and EMI work best with it
