### ISSUE TITLE
[Feature Request] Dynmap support

### ISSUE THREAD

**Issue by elhertz** [Patbox/get-off-my-lawn-reserved#15]
Claiming should create a dynmap area with a marker in the middle automatically (config to toggle this on/off).

<details>
  <summary>Example (random screenshot from google)</summary>
  
![example image from google](https://media.forgecdn.net/avatars/74/34/636163884309798871.png)
</details>

Also there could be a new augment to edit the area color and marker icon? or to add some kind of personal message to it idk
There should also be a way to hide the marker in the augment's menu (but also a way to disable this option if you want to force all your players to reveal their bases hehe).

edit: grammar

**Comment by gadget78** [comment]
this would really be a GREAT enhancement !... 
seems all data thats needed is held within `cardinal_world_components.dat` file... 
or would we need some form of API to get this working ?

**Comment by Nyphet** [comment]
I asked more info on the Dynmap Discord server [here](https://discord.com/channels/722722769950998560/1183693243595108394).  
I have currently forked this project and I'm trying to write the compat code myself, but it's proving challenging since they are two mods I know little about their inner workings.

**Comment by arnokeesman** [comment]
@Nyphet did some messing with stuff, got claims to display on dynmap!
![image](https://github.com/Patbox/get-off-my-lawn-reserved/assets/34793978/eaf28ebf-ea14-42e5-8772-b0ff88edd58b)
pushed my work so far to [this branch](https://github.com/arnokeesman/get-off-my-lawn-reserved/tree/dynmap), it's far from perfect and complete but hope it helps you get along
if you have questions feel free to ask here or find me in patboxs' discord

**Comment by Nyphet** [comment]
@arnokeesman thanks! I managed to get that working too in my fork some hours ago, but by taking a quick peek at your branch I can see some improvements I could do too, in particular how to get the `MinecraftServer`.  
I see that you too struggled on how to get the world name ahah  
My only guess is to either make a mixin/accessor to make the `serverWorldProperties.getName` visible or parse the `toString` return value from the `ServerWorld`.

**Comment by arnokeesman** [comment]
have all the basics, creating, removing and updating done
also managed to get goggle colors in there
take whatever you need and good luck with your additional features!

**Comment by Nyphet** [comment]
Thanks, the colors are a very nice touch!  
Now the only problem left for me is that Dynmap is stripping away way too many inline-styles, but this is a problem for another time ahah
