### ISSUE TITLE
Goml - Bungeecord doesn't work

### ISSUE THREAD

**Issue by AnimeTeddy** [Patbox/get-off-my-lawn-reserved#19]
Hello!
I have a Waterfall/Bungeecord network and I added a fabric server with goml in the mods. When I added goml, the server would start but no player would be able to join through /server or with a portal in the lobby. I don't know where the problems lies but I know that you can't join the server altough it is started. 
You also just get the message "you are already connecting to this server!" while trying to join with /server on the lobby server and you don't see anything in the console as well.

I hope this helps to improve your awesome mod!
Sincerely Teddy

**Comment by gadget78** [comment]
i have a servers within a velocity network, and GOML works well on both servers its on .. 
i would either remove mods on the server having issues until it resolves. maybe ?

are you using FabricProxy-Lite-2.3.0.jar ??

**Comment by gadget78** [comment]
are you able to join/get it working with JUST FabricProxyLegacy ? 
as i wasn't able to get Fabric working atall stable under waterfall, 
velocity, although a little extra work to set up, has been working 100% ..

**Comment by AnimeTeddy** [comment]
Yes I also have another redstone fabric server running and this server runs well without goml. When I add goml the server I can't join anymore. I am trying to remove the mods right now ^^.

**Comment by AnimeTeddy** [comment]
I just started the server with only fabric-api-0.66.0+1.19.2.jar, FabricProxy-Legacy-1.6.0.jar and goml-1.5.0+1.19.2.jar. The same thing happens. I can't join the server. Just nothing happens...

**Comment by gadget78** [comment]
well all i can say is that with velocity, it works.... 
maybe thats why i couldnt get waterfall to work too... ?
(so to be clear with just the 2 mods FabricAPI, and FabricProxy, you can enter ok, and then adding goml you are not able to ?)

so the fault its self is with the Fabric proxy and the way it handles things ... 
not saying that FabricProxy-Lite-2.3.0.ja is better, or doesnt have its faults, but, it does work ..

**Comment by AnimeTeddy** [comment]
The problem probably is with with fabric proxy legacy. Every mod I tried has worked so far (exluding goml), so I was at first confused. I turned the video quality a bit too low but whatever :).

https://user-images.githubusercontent.com/67074120/201748891-dc6711e8-d817-4b2f-b214-9515f669614d.mp4

**Comment by gadget78** [comment]
nice portal mods, is that on fabric too ? .... 

there are issues on proxy-lite... (with chat mods) thats the trouble with fabric, always seems to have to compromise somewhere ?..

**Comment by AnimeTeddy** [comment]
The lobby is on paper 1.19.2 with via backwards and rewind I think so that people with 1.8.9 can also join. The portals mod's named simpleportals https://github.com/XZot1K/SimplePortals.

**Comment by AnimeTeddy** [comment]
Strange thing but I am getting kicked from the server if I /op myself ?!. And I can't join anymore. I will have to look into that...

**Comment by gadget78** [comment]
same here, paper as lobby, but have just found datapack portals for fabric ..  is that glass panes for material you ising there? .. 

getting kicked as of permissions, are you using luckyperms ? ... 

also, if you have discord, maybe easier in Patbox's server ?

**Comment by AnimeTeddy** [comment]
We can do that we can also write private if you want. My DC name is Teddy#9594

**Comment by Patbox** [comment]
Polymer (library used by GOML) has it's own networking, which breaks when used with bungeecord based proxies, velocity should work better with mods in general
