### ISSUE TITLE
[1.18.2] [Fabric] Items not in Creative/REI

### ISSUE THREAD

**Issue by pewblaze** [Patbox/get-off-my-lawn-reserved#2]
![2022-03-16_20 03 06](https://user-images.githubusercontent.com/96242065/158667366-658f1a2b-50a8-46e7-963d-7bf06572d7a0.png)

Not sure if this is intended, but i dont have any items to pick. Also REI doesnt show any recipes.
I can craft the items, but i tried to test it for my server & its easier in creative or REI.

**Comment by Patbox** [comment]
Few questions:
- Is this mod on client or only server?
- Which version of polymer do you use (should be visible in F3)?

**Comment by Patbox** [comment]
I can't replicate it with mod only on server + polymer client and mod on both server and client

**Comment by pewblaze** [comment]
Client im testing my private modpack (Server will tested later). My log if this helps too:
[latest.log](https://github.com/Patbox/get-off-my-lawn-reserved/files/8272282/latest.log)

Ive got Polymer 0.2.0-beta.27

**Comment by Patbox** [comment]
Okay, it looks to be conflict with stacc mod. I will look into it

**Comment by pewblaze** [comment]
Stacc? Sorry dont know which one this should be ^^"

**Comment by Patbox** [comment]
It's library, bundled by numismatic-overhaul mod

**Comment by pewblaze** [comment]
Ah i see :)

**Comment by Patbox** [comment]
You can update now polymer manually to latest (https://github.com/Patbox/polymer#download). It should fix your issue

**Comment by Patbox** [comment]
Fixed in 1.5.0-beta.3+1.18.2
