### ISSUE TITLE
Need option to allow players to use & recover their boats inside a claim.

### ISSUE THREAD

**Issue by zjhendryx** [Patbox/get-off-my-lawn-reserved#32]
Currently, if a player sails a boat into someone's claim, then upon leaving that boat that player is unable to reenter the boat or to collect their boat and is instead met with the message informing them that the entity is protected by a claim.

I tried adding boats and the bamboo rafts into the array under "allowedEntityInteraction" in the configuration file, but it seems that GOML-Reserved is coded to not allow this yet.

My expectation would be that if boats & rafts were included in the "allowedEntityInteraction" array, then a player other than the claim owner would at least be able to "use" the boat in order then be able to sail out of the claim to then recover the boat.

**Comment by Patbox** [comment]
Changed default config to include these as interactable, also likely it was you putting wrong id in there, as all boats use `minecraft:boat` and `minecraft:chest_boat`
