### ISSUE TITLE
1.20.1 - GOML Text is using internal strings only

### ISSUE THREAD

**Issue by LokeYourC3PH** [Patbox/get-off-my-lawn-reserved#33]
In order to show what I mean better, here a screenshot:

![Screenshot 2023-06-26 143614](https://github.com/Patbox/get-off-my-lawn-reserved/assets/5807595/0a1b318f-accc-4ac7-8ea6-427f22c42689)

As you can see, all text is merely showing as "text.goml.xxx..."

This happens on Fabric 1.20.1 and the latest GOML version.

**Comment by LokeYourC3PH** [comment]
> It's one of your client mods breaking it

I suppose it's an incompatibility then. I'll figure out which one.

**Comment by Patbox** [comment]
Sent your client modlist

**Comment by Patbox** [comment]
Nothing stands out hmm. Does it work in singleplayer or also not?

**Comment by LokeYourC3PH** [comment]
> Nothing stands out hmm. Does it work in singleplayer or also not?

Apparently it's only on Multiplayer, it does not happen in Singleplayer worlds.

**Comment by Patbox** [comment]
Server list shouldn't matter. Could you install some nbt viewer mod like this one (https://modrinth.com/mod/nbttooltips)
and check the nbt of the item on client?

**Comment by LokeYourC3PH** [comment]
> Server list shouldn't matter. Could you install some nbt viewer mod like this one (https://modrinth.com/mod/nbttooltips) and check the nbt of the item on client?

I'll do that later, but I figured out something else as well. It only happens in Creative Mode, once I switched to Survival, it restored itself to normal, and stayed that way after switching into Creative again. No idea what caused/causes it.

**Comment by Patbox** [comment]
Try restarting the client. There is a chance it loaded because you tested on singleplayer

**Comment by LokeYourC3PH** [comment]
> Try restarting the client. There is a chance it loaded because you tested on singleplayer

Yup, that did it, it still shows the broken text once directly going to Multiplayer, and Survival or Creative mode doesn't matter.

**Comment by LokeYourC3PH** [comment]
Alright here you go.

Client:
![2023-06-26_18 57 44](https://github.com/Patbox/get-off-my-lawn-reserved/assets/5807595/27f52944-d61e-4bbd-aa62-b08d1187c7ca)

Server:
![2023-06-26_18 56 44](https://github.com/Patbox/get-off-my-lawn-reserved/assets/5807595/a247d33a-727a-4605-a1e1-372cc87ce248)

The NBT is clearly different, although not in a way that I can tell makes it not function.

**Comment by Patbox** [comment]
OK. The server translation part is working (see the "fallback", which has correct text). Some client mod is breaking that by ignoring this part of text json, making translation not effect it.

**Comment by LokeYourC3PH** [comment]
> Ok, I need you to generate mixin debug output. You can do that by adding `-Dmixin.debug.export=true` as java flag in your launcher. Then you need to send me ` .mixin.out/net/minecraft/class_2588.class`, as it might help me to debug that

Sure, here you go:
[class_2588.zip](https://github.com/Patbox/get-off-my-lawn-reserved/files/11870227/class_2588.zip)

**Comment by Patbox** [comment]
This class looks fine... hmm. Fun...

Could you send anything starting with `class_2477`? in same folder

**Comment by LokeYourC3PH** [comment]
> This class looks fine... hmm. Fun...
> 
> Could you send anything starting with `class_2477`? in same folder

I'll do you a better one, I'll just send you the entire class folder:
[minecraft.zip](https://github.com/Patbox/get-off-my-lawn-reserved/files/11870786/minecraft.zip)

**Comment by Patbox** [comment]
And this one looks fine... uh. Hmm

**Comment by Patbox** [comment]
See issue above. Minecraft Comes Alive breaks vanilla feature that makes MC use fallback from translatable text
