### ISSUE TITLE
[Claim Bypass] Collection of vanilla claim bypasses

### ISSUE THREAD

**Issue by ZekeSmith** [Patbox/get-off-my-lawn-reserved#36]
Hi, I have been able to find ~10 claim bypasses with vanilla I am sending all of them in this issue to not spam the issue tracker.

**Tested with GOML 1.9.2+1.20.1**

I am going to order them in how severe I think they are:

## Pistons

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/4cf77664-7f7c-42a8-94da-4d73b93446fe

## Flying Machines

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/549eff5f-fc50-48c5-8ffa-801ff1f03c6e

## Dispenser Lavacasts

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/221421f9-6943-42c0-8c93-4079662cea95

## Falling Blocks

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/20026bc4-6638-4aa7-b59e-81640d293c09

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/ba51d077-c035-4a4d-951a-09a061e976ff

This can also be done with piston block bouncers etc and can be done from the side of a claim

## Tree Growth

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/863ce593-6e14-4b09-9556-6d3600ed18fd

## Firecharge lighting stuff on fire.

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/bd3913e5-3307-4b49-ac43-05c4e71b0e36

Can be used to kill entities and in some cases I found it destroy blocks but I haven't been able to reliably reproduce that.

## Entity Killing

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/8238f620-aa56-499a-8c5c-5a5a2f85812a

## Moss Spread

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/7586dc79-ce0a-4b2c-9f29-ef19963b47f6

## TNT Activation and block interaction from dispenser

https://github.com/Patbox/get-off-my-lawn-reserved/assets/81902668/d2d8bc50-36a7-447f-b12d-848112d9b12d

**Comment by Patbox** [comment]
Going to mark it as completed, as everything excluding tree and moss got fixed. These two would be a bit pain to protect, which would be annoying for regular players

**Comment by ZekeSmith** [comment]
I might make a separate issue to track trees for later down the line as some modded trees can significantly grief claims (eg. redwoods or some of the wider trees)
