### ISSUE TITLE
[Claim Bypasses] New bugs in latest.

### ISSUE THREAD

**Issue by ZekeSmith** [Patbox/get-off-my-lawn-reserved#37]
Related to #36 

## The immortal block. (Client server desync)
The user can use a stick piston to push block into a claim then back out to make that block claimed and unbreakable by non claim owners. however on the server the block is in the claim and bugged block interacts on client only until external block update: block placed inside of claim where pushed block should be, water is put next to the block.

## Pistons can still push a block into claims.
The current changes only seem to check if its against a wall but if there is air in the border of the claim a piston can still push the block there.

## lava casting can still work on air border.
using ice and lava you can lavacast around the border of the claim.

## Flying machines break in own claim.
When a flying machine exits your own claim in breaks and wont move. but only when crossing the border.

**Comment by Patbox** [comment]
Flying machines are kinda unfixable
