### ISSUE TITLE
[BUG] multiple bugs in 1.18.2

### ISSUE THREAD

**Issue by ilkerbey-01** [Patbox/get-off-my-lawn-reserved#4]
augments pop off after restarting the server and for some reason names of blocks are glitched... also have a crash report....

https://paste.ee/p/XvuvW

**Comment by Patbox** [comment]
Could you check if installing this fixes names? https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.10%2B1.18.2/server-translations-api-1.4.10%2B1.18.2.jar

**Comment by ilkerbey-01** [comment]
will try, what about other ones?

**Comment by Patbox** [comment]
I will need little more time, but I will fix them

**Comment by Patbox** [comment]
Fixed on latest (excluding translations issues). They are most likely caused by some other mod, see https://github.com/Patbox/UniversalGraves/issues/71
