### ISSUE TITLE
Waystones inaccessible within claims.

### ISSUE THREAD

**Issue by tarkidu** [Patbox/get-off-my-lawn-reserved#5]
Waystones from the [Fabric Waystones Mod](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) are inaccessible within claims.

**Comment by Patbox** [comment]
There is a config option that should allow interactions. You just need to add all block ids to it

**Comment by tarkidu** [comment]
That's what i did. It does not work.

**Comment by Patbox** [comment]
Did you add correct ids? You need to use server side ones, not client ones

**Comment by tarkidu** [comment]
Can you clarify what you mean by server side IDs?

**Comment by ZekeSmith** [comment]
Waystones work, its just annoying the add them all manually. Is regex supported by any chance @Patbox?

**Comment by Patbox** [comment]
Nah, but I might look into adding that
